### ISSUE TITLE
caInclude fails

### ISSUE THREAD

**Issue by prjemian** [caqtdm/caqtdm#56] opened 2021-04-01 15:48 UTC
As described in https://github.com/BCDA-APS/epics-bluesky-vm/issues/3, the `caInclude` widget fails for me on the [synApps *calc* record ](https://github.com/epics-modules/calc) `userCalcs10.ui` support screen.  

Using caQtDM V4.3.1_Development_7f5cdccb Build=MAR 29 2021 01:00 on Ubuntu 20.04.1LTS

![Clipboard01](https://user-images.githubusercontent.com/2279984/113318609-3d0f4680-92d6-11eb-9e8a-e5938a149459.png)

Each row in the table is expected to look like this one:

![Clipboard02](https://user-images.githubusercontent.com/2279984/113318670-4dbfbc80-92d6-11eb-80d1-f785bc21ef16.png)

To assemble a system that replicates this problem, start a synApps IOC in a docker container using the [`start_xxx.sh`](https://github.com/prjemian/epics-docker/tree/main/n3_synApps#one-time-setup) script:

```sh
cd ~/Downloads
 wget https://raw.githubusercontent.com/prjemian/epics-docker/master/n3_synApps/start_xxx.sh
 wget https://raw.githubusercontent.com/prjemian/epics-docker/master/n3_synApps/remove_container.sh
```

Start the `gp:` IOC in a container with this command:

    ~/Downloads/start_xxx.sh gp

Then start a new caQtDM session:

    /tmp/docker_ioc/iocgp/xxx-R6-1/start_caQtDM_xxx &

Click the *Tools* button, then from the *userCalc* popup menu button, select *user calcs 1-10* and the problem screen will appear.

**Comment by prjemian** [comment] 2021-04-01 15:49
My [observation](https://github.com/BCDA-APS/epics-bluesky-vm/issues/3#issuecomment-811989921) is that

> *WHEN* the corresponding `.adl` file is copied into the `/tmp/docker_ioc/synapps-6.1/screens/ui/` directory, the `caInclude` widget works properly.  Looks like a problem with caQtDM that happens when a `.adl` file is requested and not found but a `.ui` file is available.  

The existing `.ui` file is not recognized as a caQtDM file.

**Comment by prjemian** [comment] 2021-04-01 15:53
Repeating these steps on a different workstation with caQtDM V4.1.6_Development_6a6a487a Build=Jul 21 2017 23:34 and there is no problem.  Has a regression has been introduced between these two versions?

**Comment by HelgeBrands** [comment] 2021-04-01 15:53
ok I will check what the problem is.

**Comment by HelgeBrands** [comment] 2021-04-01 15:55
its the internal version of the adl converter. But you can compile caQtDM with the flag not to use the internal converter. Hopefully then this problem will not be there.

**Comment by prjemian** [comment] 2021-04-01 15:57
I'll look for that flag and add it my [build instructions](https://github.com/BCDA-APS/epics-bluesky-vm/blob/main/planning.md#caqtdm)

**Comment by prjemian** [comment] 2021-04-01 16:01
Can you help me find the flag?  I'm not so lucky today:

```sh
  483  cd /usr/local/epics/opi/src/caqtdm/
  484  git grep -i ignore | less
  485  git grep -i ignore | grep -i convert
  486  git grep -i ignore | grep -i adl
  487  git grep -i ignore | grep -i medm
  488  git grep -i ignore | less
  489  git grep IGNORE | less
  490  git grep MEDM | less
  491  git grep MEDM | grep -i convert
```

**Comment by prjemian** [comment] 2021-04-01 16:03
`ADL_EDL_FILES`?

**Comment by HelgeBrands** [comment] 2021-04-01 16:04
Yes this is it

**Comment by prjemian** [comment] 2021-04-01 16:38
Commented out the three lines that defined `ADL_EDL_FILES` from `all.pro` and did a complete rebuild (`./caQtDM_CleanAll && ./caQtDM_BuildAll && ./caQtDM_Install`) in the source directory.  Repeated my procedure to load the `userCalcs1.ui` screen and got the same problem (as shown in the logs):

```sh
01-04-2021 11:35:08 sorry -- specified file /tmp/docker_ioc/synapps-6.1/screens/ui/userCalcs_line.ui is not a med or edm file
01-04-2021 11:35:08 could not load include file /tmp/docker_ioc/synapps-6.1/screens/ui/userCalcs_line.ui
```

**Comment by HelgeBrands** [comment] 2021-04-01 17:54
there some problems with the search path + cainclude; to solve your problem now you could add in the include widget the correct filename + extension. Without extension and the .adl extension the cainclude makes things wrong.

**Comment by prjemian** [comment] 2021-04-01 18:43
Thanks.  I'll use a `sed` command to replace `.adl` with `.ui` in all my caQtDM screens in this container.  These screens come from various synApps modules and were converted with adl2ui at some time in the past.  Was the adl2ui converter ever modified to make these changes?  Anyway, if that works, then it is time to make these changes in new pull requests for each of the affected synApps modules.

**Comment by prjemian** [comment] 2021-04-01 21:46
FYI, change all the screen files:

```sh
cd /tmp/docker_ioc/synapps-6.1/screens/ui
for f in $(ls *.ui); do
    echo Converting $f ...
    sed -i s:'.adl':'.ui':g ./$f
done
```

**Comment by HelgeBrands** [comment] 2021-04-06 09:39
I updates caQtDM_Lib for a better check/search #[ce7c467]. Can you check if the your problem is gone?

**Comment by HelgeBrands** [comment] 2021-04-06 12:09
and a second info the adl2ui converter is handling this "problem" correctly  #[a70faad]. So this problem should be fixed.

**Comment by prjemian** [comment] 2021-04-06 14:40
I do not believe the problem is gone.  See this screen view:
![Clipboard01](https://user-images.githubusercontent.com/2279984/113727669-f4cb9c00-96ba-11eb-9a37-36ea3c686e8e.png)

procedure:

1. `cd /usr/local/epics/opi/src/caqtdm`
2. `git stash`
3. `git pull`  --> pulled new changes

```sh
(base) prjemian@zap:.../src/caqtdm$ git pull
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 20 (delta 14), reused 20 (delta 14), pack-reused 0
Unpacking objects: 100% (20/20), 3.06 KiB | 241.00 KiB/s, done.
From https://github.com/caqtdm/caqtdm
   b2112a2b..0479b51e  Development -> origin/Development
Updating b2112a2b..0479b51e
Fast-forward
 caQtDM_Lib/caQtDM_Plugins/bsread/bsread_decode.cpp |  6 +++---
 caQtDM_Lib/caQtDM_Plugins/epics3/epicsSubs.c       |  8 ++++++--
 caQtDM_Lib/src/caqtdm_lib.cpp                      | 11 +++++++----
 caQtDM_QtControls/src/catable.cpp                  |  9 ++++++++-
```

4. `git status` -> shows on branch *Development*
5. [`source ./setup_environment.sh`](https://github.com/BCDA-APS/epics-bluesky-vm/blob/7-scripts/.create/05b_build_caqtdm.sh#L17-L68)
6. `bash ./caQtDM_CleanAll`
7. `bash ./caQtDM_BuildAll`
8. `bash ./caQtDM_Install`

Then started my session as before.

I'll apply this change and test again:

```sh
# pending: https://github.com/caqtdm/caqtdm/issues/56
sed -i s:'caQtDM_Lib.depends += caQtDM_Parsers':'# caQtDM_Lib.depends += caQtDM_Parsers':g ./all.pro
```

**Comment by prjemian** [comment] 2021-04-06 14:54
Still no solution after this last `sed` command.  So, removed entire caqtdm source directory and repeated full installation steps (starting with `git clone`).

Note that these tests are executed on a directory with screens that have not been modified as described [above](https://github.com/caqtdm/caqtdm/issues/56#issuecomment-812189450).  (That is, the `.ui` files contain references to `.adl` screen files which are not available in the display path.)

**Comment by HelgeBrands** [comment] 2021-04-06 16:28
sorry I oversee the opposite  and the triggered conversion. This is now fixed #[9abde97]

**Comment by prjemian** [comment] 2021-04-06 17:41
You fixed it for me!  Thanks!
![Clipboard01](https://user-images.githubusercontent.com/2279984/113755011-703a4700-96d5-11eb-9b54-bee4985ac1b4.png)

**Comment by HelgeBrands** [comment] 2021-04-08 08:40
ok then I can close this

**Closed by HelgeBrands** 2021-04-08 08:40 UTC
